#page title
page_title                                : Visamplify                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6472035099                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/ca/app/visamplify/id6472035099                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.visamplify.app                                          # Enter Google Play Store URL.
presskit_download_link                    :                                        # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Visamplify                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Introducing the ultimate migrant hub! Connect anonymously, share stories, find support. Join public and private groups, access immigration blogs—all in one place. Stop endless scrolling on Facebook, Whatsapp, Reddit—Get your immigration answers here!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : #Visamplify                               
your_link                                 : #http://visamplify.com                     
your_city                                 :                                 
email_address                             : visamplify@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : Visamplify07
github_username                           : 
youtube_username                          :
mastodon_link                             : 


# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Posts
    description                           : Share your visa and immigration-related questions, experiences, and tips with the Visamplify community. Whether you're seeking advice or offering insights, posting allows you to engage with others anonymously, fostering a supportive environment for knowledge exchange.
    fontawesome_icon_name                 : list
    
  - title                                 : Visa Cafes
    description                           : Join public or private Visa Cafes, interactive group chats tailored to specific visa and immigration topics or regions. Engage in real-time conversations, exchange information, and build connections with fellow community members.
    fontawesome_icon_name                 : user-group

  - title                                 : Blogs
    description                           : Stay informed and up-to-date with the latest news, updates, and insights on visa and immigration topics through curated blogs within the Visamplify app. Access informative articles, expert opinions, and relevant resources to enhance your understanding of visa processes and immigration policies.
    fontawesome_icon_name                 : newspaper

  - title                                 : Important Links
    description                           : Access a curated collection of immigration-related resources and add your own important links to contribute to the community's knowledge base. Whether it's official government websites, educational resources, or reputable organizations, the Important Links feature serves as a comprehensive repository for valuable information relevant to visa and immigration processes.
    fontawesome_icon_name                 : link

  - title                                 : Data Center
    description                           : Explore and share links to data sources, statistics, and reports related to immigration trends, policies, and demographics. The Data Center feature empowers users to access factual information and insights to better understand the dynamics of immigration in various regions and make informed decisions about their visa and immigration plans.
    fontawesome_icon_name                 : database
  
  - title                                 : #Feature List
    description                           : #Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #star

  - title                                 : #Smart App Banner
    description                           : #Display a smart app banner on iOS devices.
    fontawesome_icon_name                 : #arrow-alt-circle-down

  - title                                 : #Social Links
    description                           : #Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #link

  - title                                 : #FontAwesome Support
    description                           : #Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : #info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

include: 
  - ".well-known"

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
